"use client";
import {useEffect,useMemo,useState} from "react";
import Nav from "@/components/Nav";
import {EXECUTABLE_ROUTES} from "@/lib/route-catalog";
type Launch={token:string;name:string;symbol:string;creator:string;targetSymbol:string;targetName:string;policy:number};
const policies=["Weighted raffle","Equal lottery","Pro-rata"];
export default function Explore(){const[launches,setLaunches]=useState<Launch[]>([]);const[loaded,setLoaded]=useState(false);const[query,setQuery]=useState("");const[market,setMarket]=useState("ALL");useEffect(()=>{fetch("/api/routy-launches",{cache:"no-store"}).then(r=>r.json()).then(d=>setLaunches(d.launches||[])).catch(()=>setLaunches([])).finally(()=>setLoaded(true))},[]);const rows=useMemo(()=>launches.filter(l=>{const q=query.trim().toLowerCase();return(!q||l.name.toLowerCase().includes(q)||l.symbol.toLowerCase().includes(q)||l.token.toLowerCase().includes(q)||l.creator.toLowerCase().includes(q))&&(market==="ALL"||l.targetSymbol===market)}),[launches,query,market]);return <main className="shell"><Nav/><div className="wrap console-page">
<header className="page-head"><div className="page-head-copy"><span className="eyebrow">Routed launches</span><h1>Explore.</h1><p className="lead">Discover tokens whose creator-fee flow is connected to transparent Stock Token routes on Robinhood Chain.</p></div><a className="primary" href="/launch">Launch route</a></header>
<section className="proof-grid">{EXECUTABLE_ROUTES.map(r=><article className="proof-card" key={r.symbol}><span className="micro">VERIFIED MARKET</span><strong>{r.symbol} / USDG</strong><p>{r.name} route · PoolKey verified</p></article>)}</section>
<section className="section"><div className="section-head"><div><span className="micro">MARKET DISCOVERY</span><h2>Verified markets first.</h2></div><p className="section-copy">Routy only surfaces launch targets backed by a verified route configuration. More markets can be added without changing the public launch flow.</p></div>
<div className="market-directory">{EXECUTABLE_ROUTES.map(r=><article key={r.symbol}><div className="market-icon">{r.symbol.slice(0,1)}</div><div><b>{r.symbol}</b><span>{r.name}</span></div><span className="pill">Verified</span></article>)}</div></section>
<section className="section"><div className="terminal-filterbar"><div className="terminal-search"><span>/</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Routy token, address or creator"/></div><div className="tabs"><button className={"tab "+(market==="ALL"?"active":"")} onClick={()=>setMarket("ALL")}>All</button>{EXECUTABLE_ROUTES.map(r=><button key={r.symbol} className={"tab "+(market===r.symbol?"active":"")} onClick={()=>setMarket(r.symbol)}>{r.symbol}</button>)}</div><span className="terminal-count">{rows.length} ROUTES</span></div>{rows.length?<div className="routy-launch-list"><div className="routy-launch-head"><span>TOKEN</span><span>ROUTE</span><span>REWARD POLICY</span><span>CREATOR</span><span>STATUS</span></div>{rows.map(l=><a className="routy-launch-row" href={"/token/"+l.token} key={l.token}><div className="routy-token-id"><div className="asset-logo">{l.symbol?.[0]||"R"}</div><div><b>{"$"+l.symbol}</b><span>{l.name}</span></div></div><div><b>→ {l.targetSymbol}</b><span>{l.targetName}</span></div><div><b>{policies[l.policy]||"Unknown"}</b><span>Policy {l.policy}</span></div><code>{l.creator.slice(0,6)}…{l.creator.slice(-4)}</code><span className="terminal-ok">● PROVISIONED</span></a>)}</div>:<div className="empty-state"><span className="micro">{loaded?"ROUTY LAUNCHES":"SYNCING CHAIN"}</span><h3 style={{marginTop:10}}>{loaded?"No matching Routy tokens yet.":"Reading ProtocolLauncher events…"}</h3><p className="muted">{loaded?"The first successfully provisioned Routy token will appear here automatically. Assets are kept separately in the Stock Token registry.":"This feed only displays verified onchain launches."}</p>{loaded&&<a className="secondary" href="/launch">Launch first route →</a>}</div>}</section>
</div></main>}