"use client";
import {useEffect,useMemo,useState} from "react";
import Nav from "@/components/Nav";
import DataNotice from "@/components/DataNotice";
import {useApiResource} from "@/lib/use-api-resource";
import TokenLogo from "@/components/TokenLogo";
import {getInjectedProvider} from "@/lib/ethereum-provider";
type Launch={token:string;name:string;symbol:string;creator:string;targetSymbol:string;targetName:string;vault:string;router:string;distributor:string;policy:number;createdAt:number|null;transactionHash:string};
const short=(v:string)=>v.slice(0,6)+"…"+v.slice(-4);
const EMPTY_LAUNCHES:Launch[]=[];
export default function PortfolioPage(){
 const[account,setAccount]=useState("");const resource=useApiResource<{launches:Launch[];generation:string;historyComplete:boolean}>("/api/routy-launches");const launches=resource.data?.launches||EMPTY_LAUNCHES;const loaded=!resource.loading&&!resource.error;
 useEffect(()=>{const p=getInjectedProvider();const sync=()=>p?.request<string[]>({method:"eth_accounts"}).then(a=>setAccount(a?.[0]||"")).catch(()=>{});const id=window.setTimeout(sync,0);p?.on?.("accountsChanged",sync);return()=>{window.clearTimeout(id);p?.removeListener?.("accountsChanged",sync)}},[]);
 const mine=useMemo(()=>account?launches.filter(l=>l.creator.toLowerCase()===account.toLowerCase()):[],[account,launches]);
 return <main className="shell"><Nav/><div className="wrap console-page"><header className="page-head"><div className="page-head-copy"><span className="eyebrow">Wallet console</span><h1>Portfolio</h1><p className="lead">Provisioned Routy routes associated with the connected creator wallet. Unverified balances are never synthesized.</p></div><span className="pill">{account?short(account):"Wallet not connected"}</span></header><DataNotice error={resource.error} retry={resource.reload}/>
 <div className="proof-grid"><article className="proof-card"><span className="micro">YOUR ROUTES</span><strong>{account&&loaded?mine.length:"—"}</strong><p>Provisioned creator launches</p></article><article className="proof-card"><span className="micro">TARGET MARKETS</span><strong>{account&&loaded?new Set(mine.map(x=>x.targetSymbol)).size:"—"}</strong><p>Distinct Stock Token routes</p></article><article className="proof-card"><span className="micro">DATA SOURCE</span><strong>Chain</strong><p>Verified provisioning events</p></article><article className="proof-card"><span className="micro">NETWORK</span><strong>4663</strong><p>Robinhood Chain</p></article></div>
 <section className="section"><div className="section-head"><div><span className="micro">CREATOR ROUTES</span><h2>{account?"Wallet-linked deployments.":"Connect wallet to resolve portfolio."}</h2></div></div>
 {account&&mine.length?<div className="routy-launch-list"><div className="routy-launch-head"><span>TOKEN</span><span>ROUTE</span><span>VAULT</span><span>CREATED</span><span>STATUS</span></div>{mine.map(l=><a className="routy-launch-row" href={"/token/"+l.token} key={l.token}><div className="routy-token-id"><TokenLogo token={l.token} symbol={l.symbol} size={38}/><div><b>{"$"+l.symbol}</b><span>{l.name}</span></div></div><div><b>→ {l.targetSymbol}</b><span>{l.targetName}</span></div><code>{short(l.vault)}</code><span>{l.createdAt?new Date(l.createdAt*1000).toLocaleDateString():"—"}</span><span className="terminal-ok">● PROVISIONED</span></a>)}</div>:<div className="empty-state"><span className="micro">{!account?"WALLET REQUIRED":loaded?"NO CREATOR ROUTES":"SYNCING CHAIN"}</span><h3 style={{marginTop:10}}>{!account?"Connect your wallet from the header.":resource.error?"Live data unavailable":loaded?"No Routy routes for this wallet yet.":"Reading protocol events…"}</h3><p className="muted">Creator routes appear automatically after successful provisioning.</p></div>}
 </section></div></main>
}