import Nav from "@/components/Nav";
export default function ProtocolDocs(){return <main className="shell"><Nav/><div className="wrap console-page">
<header className="page-head"><div className="page-head-copy"><span className="eyebrow">Docs / protocol</span><h1>Protocol.</h1><p className="lead">How Routy Fund connects token launches, fee routing, Stock Token acquisition and community rewards.</p></div><a className="secondary" href="/docs">← Docs</a></header>
<section className="section"><div className="terminal-doc-article">
<h2 id="launch">Launch & automatic setup</h2><p>The creator chooses the token identity, Stock Token target and reward policy, then signs one Pons V2 launch from their wallet. That signature commits to the target and policy through the deterministic fee-router address. Routy verifies the confirmed launch before adding it to its setup queue.</p><p>The operator prepares the fee router, provisions the vault and distributor, attaches the verified PoolKey, and activates execution and rewards. Setup runs every minute; confirmation times, queue load and infrastructure availability can delay completion. A submitted launch can be resumed from the same browser without signing a second launch.</p>
<h2>Verified markets</h2><p>The launch interface shows the current supported Stock Token targets, all paired with USDG. Each route has a pinned PoolKey and requires AssetRegistry approval and matching target and quote oracle feeds. A verified catalog entry does not guarantee current liquidity or an available execution price.</p>
<h2>Direct creator-fee routing</h2><p>Pons credits earned creator fees to the route&apos;s fee router. Permissionless harvesting sends 80% of those fees to the asset vault and 20% to the protocol treasury. This split applies to earned creator fees, not the token supply, launch fee or wallet balance. Direct unrelated deposits do not increase the vault&apos;s earned swap budget.</p>
<h2>Stock Token acquisition</h2><p>The keeper attempts guarded swaps from earned USDG into the immutable target Stock Token. Registry, trading-halt, oracle freshness, price deviation, slippage, deadline and PoolKey checks must pass, and the executor must be unpaused. Purchased Stock Tokens are forwarded to the route&apos;s reward distributor.</p>
<h2 id="rewards">Automatic wallet rewards</h2><p>The reward worker runs every five minutes. It reconstructs holder balances from complete transfer history at a pinned chain snapshot, excluding the creator and configured protocol addresses. It pushes funded Stock Tokens directly to eligible recipient wallets; holders do not claim.</p><p>Weighted raffle selects one wallet with odds proportional to its token balance. Equal lottery selects one eligible wallet with equal odds. Pro-rata allocates to all eligible holders in proportion to their balances, subject to integer rounding. A funded reward balance and eligible holders are required; owning a token alone does not guarantee a payment.</p><p>Reward batches use cumulative payout amounts and a saved allocation plan so interrupted runs can continue the same distribution. Raffle selection uses a deterministic block-based seed and a trusted keeper; it is not independently verifiable randomness.</p>
<h2>Operational trust</h2><p>Users keep control of their wallets. The configured operator and keeper control setup and reward publication; the keeper is trusted to submit the published allocations. Automation also depends on a funded operator wallet, RPC access, the setup queue and scheduled workers. Live deployment and pause state are shown in Release status.</p>
<h2>Data policy</h2><p>Routy intentionally avoids fabricated market cap, volume, fee, reward or claim balances. Empty or unavailable metrics remain blank until a reliable source exists.</p>
</div></section></div></main>}
