import Nav from "@/components/Nav";
export default function ProtocolDocs(){return <main className="shell"><Nav/><div className="wrap console-page">
<header className="page-head"><div className="page-head-copy"><span className="eyebrow">Docs / protocol</span><h1>Protocol.</h1><p className="lead">How Routy Fund connects token launches, fee routing, Stock Token acquisition and community rewards.</p></div><a className="secondary" href="/docs">← Docs</a></header>
<section className="section"><div className="terminal-doc-article">
<h2 id="launch">Launch & provisioning</h2><p>Tokens are launched through the configured Pons V2 factory. Routy does not custody creator wallets or private keys. After launch, Routy queues verified launches for automatic V4 route provisioning against the selected supported market.</p>
<h2>Verified markets</h2><p>Production markets are sourced from the executable V4 route catalog. Every enabled route is tied to an approved asset entry, oracle configuration and verified PoolKey; the interface should be treated as the source of the currently enabled set rather than this document.</p>
<h2>Fee routing</h2><p>Routy separates routed creator-fee flow between the asset-vault path and protocol treasury according to the configured protocol split. The current interface displays the 80/20 allocation used by the deployed system.</p>
<h2>Execution controls</h2><p>Value-moving execution is guarded by registry checks, oracle feeds, deviation controls, verified PoolKey data and a pausable SwapExecutor. The V4 executor is pausable and route setup configures verified PoolKey data before execution is enabled. Route provisioning and reward activation are automated; swap execution remains constrained by the deployed executor permissions and onchain safeguards.</p>
<h2 id="rewards">Reward policies</h2><p>Each route selects one reward mode: weighted raffle, equal lottery or pro-rata. V4 reward status and allocations are derived from verified onchain route, distributor and holder-snapshot data.</p>
<h2>Data policy</h2><p>Routy intentionally avoids fabricated market cap, volume, fee, reward or claim balances. Empty or unavailable metrics remain blank until a reliable source exists.</p>
</div></section></div></main>}